---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  labels:
    name: locust
spec:
  replicas: 2
  selector:
    matchLabels:
      name: locust
      app.kubernetes.io/name: locust
  template:
    metadata:
      labels:
        name: locust
        app.kubernetes.io/name: locust
    spec:
      containers:
      - name: locust
        image: iad.ocir.io/ociateam/jeevan/mushop-load:snapshot
        imagePullPolicy: Always
        ports:
          - containerPort: 8089
        args: ["-h", "edge", "-c", "1", "-r", "1"]
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: locust
  labels:
    name: locust
spec:
  selector:
    name: locust
  ports:
  - port: 80
    targetPort: 8089


